spring:
  datasource:
    url: jdbc:h2:mem:testdb;TRACE_LEVEL_FILE=0
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/

camunda:
  bpm:
    database:
      type: h2
      schema-update: true
    admin-user:
      id: demo
      password: demo
